In [5]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

corpus =[
    "This is the first document",
    "This is the second second document",
    "And the third one",
    "Is this the first document?"]

vect1 = CountVectorizer().fit(corpus)
tf = vect1.transform(corpus)

feature_names = vect1.get_feature_names()
print("Terms:{}".format(feature_names[:]))
print(tf.toarray(), "\n")

vect2 = TfidfVectorizer().fit(corpus)
tfidf = vect2.transform(corpus)
print(tfidf.toarray())

Terms:['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]] 

[[0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]
 [0.         0.27230147 0.         0.27230147 0.         0.85322574
  0.22262429 0.         0.27230147]
 [0.55280532 0.         0.         0.         0.55280532 0.
  0.28847675 0.55280532 0.        ]
 [0.         0.43877674 0.54197657 0.43877674 0.         0.
  0.35872874 0.         0.43877674]]


In [9]:
from sklearn.feature_extraction.text import CountVectorizer

bard_words = ["The fool doth think he is wise",
             "but the wise man knows himself to be a fool"]

cv = CountVectorizer(ngram_range = (1,1)).fit(bard_words)
print("어휘사전의 크기:{}".format(len(cv.vocabulary_)))
print("어휘사전: \n{}".format(cv.get_feature_names()))
print("변환된 데이터:\n{}".format(cv.transform(bard_words).toarray()))

어휘사전의 크기:13
어휘사전: 
['be', 'but', 'doth', 'fool', 'he', 'himself', 'is', 'knows', 'man', 'the', 'think', 'to', 'wise']
변환된 데이터:
[[0 0 1 1 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 0 1 0 1 1 1 0 1 1]]


In [11]:
cv = CountVectorizer(ngram_range = (2,2)).fit(bard_words)
print("어휘사전의 크기:{}".format(len(cv.vocabulary_)))
print("어휘사전: \n{}".format(cv.get_feature_names()))
print("변환된 데이터:\n{}".format(cv.transform(bard_words).toarray()))

어휘사전의 크기:14
어휘사전: 
['be fool', 'but the', 'doth think', 'fool doth', 'he is', 'himself to', 'is wise', 'knows himself', 'man knows', 'the fool', 'the wise', 'think he', 'to be', 'wise man']
변환된 데이터:
[[0 0 1 1 1 0 1 0 0 1 0 1 0 0]
 [1 1 0 0 0 1 0 1 1 0 1 0 1 1]]


In [13]:
cv = CountVectorizer(ngram_range = (1,3)).fit(bard_words)
print("어휘사전의 크기:{}".format(len(cv.vocabulary_)))
print("어휘사전: \n{}".format(cv.get_feature_names()))
print("변환된 데이터:\n{}".format(cv.transform(bard_words).toarray()))

어휘사전의 크기:39
어휘사전: 
['be', 'be fool', 'but', 'but the', 'but the wise', 'doth', 'doth think', 'doth think he', 'fool', 'fool doth', 'fool doth think', 'he', 'he is', 'he is wise', 'himself', 'himself to', 'himself to be', 'is', 'is wise', 'knows', 'knows himself', 'knows himself to', 'man', 'man knows', 'man knows himself', 'the', 'the fool', 'the fool doth', 'the wise', 'the wise man', 'think', 'think he', 'think he is', 'to', 'to be', 'to be fool', 'wise', 'wise man', 'wise man knows']
변환된 데이터:
[[0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 1 1 1 0 0 0
  1 0 0]
 [1 1 1 1 1 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1
  1 1 1]]


In [1]:
import nltk
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [1]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

ps=PorterStemmer()
example_words = ["puthon", "pythoner","pythoning","pythoned", "pythonly"]
for stem in example_words:
    print(ps.stem(stem))

puthon
python
python
python
pythonli


In [ ]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

new_text="It is very important to be very pythonly while you are pythoning with python"

words = word_tokenize(new_text)
print(words)

for w in words:
    print(ps.stem(w))

In [14]:
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize

new_text="It is very important to be very pythonly while you are pythoning with python"

words = word_tokenize(new_text)
result = [ps.stem(w) for w in words]
print(result)

['it', 'is', 'veri', 'import', 'to', 'be', 'veri', 'pythonli', 'while', 'you', 'are', 'python', 'with', 'python']


In [15]:
import nltk
from nltk import word_tokenize
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer

stemmer = PorterStemmer()
def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stemmed=[]
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

vect = CountVectorizer(tokenizer = tokenize, stop_words='english')

vect.fit(["The swimmer likes swimming."])

sen1 = vect.transform(["The swimmer likes swimming."])
sen2 = vect.transform(["The swimmer swims . ."])
print(vect.get_feature_names())
print(sen1.toarray())
print(sen2.toarray())

['.', 'like', 'swim', 'swimmer']
[[1 1 1 1]]
[[2 0 1 1]]


In [16]:
from sklearn.datasets import load_files
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
import nltk
from nltk import word_tokenize
from nltk.stem.porter import PorterStemmer
import numpy as np
import re

reviews_train = load_files("/Users/soominkang/Downloads/aclImdb 2/train")
text_train, y_train = reviews_train.data, reviews_train.target

reviews_test = load_files("/Users/soominkang/Downloads/aclImdb 2/test")
text_test, y_test = reviews_test.data, reviews_test.target
print("테스트 데이터의 문제수: {}".format(len(text_test)))
print("클래스별 샘플 수(테스트 데이터): {}".format(np.bincount(y_test)))

text_train = [doc.replace(b"<br /n>", b" ") for doc in text_train]
text_test = [doc.replace(b"<br /n>", b" ") for doc in text_test]

stemmer = PorterStemmer()

def tokenize(text):
    tokens = nltk.word_tokenize(text)
    stemmed=[]
    for item in tokens:
        stemmed.append(stemmer.stem(item))
    return stemmed

vect = CountVectorizer(tokenizer = tokenize, stop_words="english").fit(text_train)
x_train = vect.transform(text_train)
x_test = vect.transform(text_test)

clf = LogisticRegression(max_iter=500)
clf.fit(x_train, y_train)
pre = clf.predict(x_test)

ac_score = accuracy_score(y_test, pre)
print("정답률 = ", ac_score)

테스트 데이터의 문제수: 25000
클래스별 샘플 수(테스트 데이터): [12500 12500]
정답률 =  0.85848


/Users/soominkang/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
!pip list

Package                            Version
---------------------------------- --------------------
alabaster                          0.7.12
anaconda-client                    1.9.0
anaconda-navigator                 2.1.1
anaconda-project                   0.10.1
anyio                              2.2.0
appdirs                            1.4.4
applaunchservices                  0.2.1
appnope                            0.1.2
appscript                          1.1.2
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asn1crypto                         1.4.0
astroid                            2.6.6
astropy                            4.3.1
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.7
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      